New test:
try to have libprotobuf included in wheel
back to 3.10.0 as 3.13 is not better regarding test fails

diff --git a/docker/base_runner/Dockerfile b/docker/base_runner/Dockerfile
--- a/docker/base_runner/Dockerfile
+++ b/docker/base_runner/Dockerfile
@@ -43,9 +43,9 @@ RUN protoc --version
 # Build the python part
 WORKDIR python
 
-RUN python3 setup.py build --cpp_implementation
-RUN python3 setup.py test --cpp_implementation || echo "Errors in python test"
-RUN python3 setup.py sdist bdist_wheel --cpp_implementation
+RUN python3 setup.py build --cpp_implementation --compile_static_extension
+RUN python3 setup.py test --cpp_implementation --compile_static_extension || echo "Errors in python test"
+RUN python3 setup.py sdist bdist_wheel --cpp_implementation --compile_static_extension
 
 
 
